Why does the following code...

```
def execute(block)
  block.call
end

execute { puts "hello from inside the execute method!" }
```

Give us the following error when we run it?

```
block.rb1:in `execute': wrong number of arguments (0 for 1) (ArgumentError)
from test.rb:5:in `<main>'
```

`block` hasn't been indicated as a parameter to the execute method on line 1 as it's missing `&`. When the execute method is called on line 5, it's waiting for us to pass an argument (`execute(insert_argument_here)`) but we don't, so the error 'wrong number of arguments (0 for 1) informs us as such.